### ISSUE TITLE
Typespecs does not match

### ISSUE THREAD

**Issue by tino415** [ivalentinee/fast_xlsx_exporter#1]
I'm using dialyzer on my project and I get a lot of errors for this lib mainly because typespecs does not match definitions, for instance `shared_strings_context() :: {{:file.io_device(), integer()}, dictionary()}` and at the end of initialize `{fd, shared_string_count, dictionary}`

**Comment by ivalentinee** [comment]
Thanks. I'll try to fix it in few days.

**Comment by ivalentinee** [comment]
Fixed with [0.2.2](https://hex.pm/packages/fast_xlsx_exporter/0.2.2).

Tested on Elixir 1.11.2 with Dialyxir 1.0.0.

If dialyzer still reports errors, please reopen this issue.
